# Generated by Django 4.2.4 on 2023-09-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("klime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="grade",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
