# Generated by Django 4.2.4 on 2023-09-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klime', '0002_alter_problem_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='wall_id',
            new_name='wall',
        ),
    ]
