# Generated by Django 4.2.4 on 2023-08-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klime', '0002_wall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wall',
            old_name='user',
            new_name='user_id',
        ),
    ]
