# Generated by Django 4.2.4 on 2023-08-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klime', '0003_rename_user_wall_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vectors', models.CharField(max_length=1000)),
                ('wall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klime.wall')),
            ],
        ),
    ]
