# Generated by Django 4.2.4 on 2023-08-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klime', '0004_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wall',
            old_name='user_id',
            new_name='user',
        ),
    ]
